### ISSUE TITLE
Block level DV check

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/sunburst-chip#13]
I'm checking block-level DV for the blocks integrated from OpenTitan into Sunburst chip and making sure that the pass rate is similar under VCS and Xcelium:

- [x] Aon timer see: https://github.com/lowRISC/sunburst-chip/issues/13#issuecomment-2648147335
- [x] GPIO see: https://github.com/lowRISC/sunburst-chip/issues/13#issuecomment-2653825844
- [x] #42
- [x] Pattgen see: https://github.com/lowRISC/sunburst-chip/issues/13#issuecomment-2654049570
- [x] PWM see: https://github.com/lowRISC/sunburst-chip/issues/13#issuecomment-2657306101
- [x] RV PLIC: formal only https://opentitan.org/book/hw/top_earlgrey/ip_autogen/rv_plic/doc/dv/index.html
- [x] RV timer see: https://github.com/lowRISC/sunburst-chip/issues/13#issuecomment-2665574329
- [x] SPI host see: https://github.com/lowRISC/sunburst-chip/issues/13#issuecomment-2666115510
- [x] UART see: https://github.com/lowRISC/sunburst-chip/issues/13#issuecomment-2668371745
- [x] #54

Some more blocks that don't have block-level DV (yet):
- CHERIoT Ibex
- CHERIoT hardware revoker
- CHERIoT-enabled debug module
- Sonata revocation control
